WORKDIR /tmp

RUN yum groupinstall -y 'Development Tools' && \
    yum install -y bzip2-devel freetype-devel libjpeg-devel libpng-devel libtiff-devel giflib-devel zlib-devel ghostscript-devel djvulibre-devel libwmf-devel jasper-devel libtool-ltdl-devel libX11-devel libXext-devel libXt-devel lcms-devel libxml2-devel librsvg2-devel OpenEXR-devel php-devel && \
    yum install -y wget ghostscript && \
    wget https://github.com/ImageMagick/ImageMagick/archive/7.0.9-10.tar.gz && \
    tar xvzf 7.0.9-10.tar.gz && \
    cd ImageMagick-7.0.9-10 && \
    ./configure && \
    make && \
    make install && \
    rm -Rf ImageMagick-7.0.9-10 7.0.9-10.tar.gz

ENV MAGICK_MEMORY_LIMIT 1GB
ENV MAGICK_THREAD_LIMIT 1
ENV MAGICK_DISK_LIMIT 10G